### ISSUE TITLE
Errors when Compiling

### ISSUE THREAD

**Issue by Colway** [DillonGrech/Metatrader-Strategies#1]
';' - unexpected end of program	test0.mq5	387	13
'{' - unbalanced parentheses	test0.mq5	339	1
'AdjustTsl' - undeclared identifier	test0.mq5	152	11
',' - unexpected token	test0.mq5	152	33
'TicketNumber' - some operator expected	test0.mq5	152	21
',' - unexpected token	test0.mq5	152	45
')' - unexpected token	test0.mq5	152	59
expression has no effect	test0.mq5	152	47

**Comment by DillonGrech** [comment]
Tested all versions of the EA's provided in the repository and complied without any issues. Please ensure that all content has been copied over correctly.
